# Site settings
description: This is a new starter to be implemented.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://findcyrus.github.io/" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Cyrus Cai1
user_description: Cyrus Cai. I'm an early bird.
user_title: Cyrus Cai2
email: cyrus_cai@epam.com
twitter_username: Cyrus3
github_username:  Cyrus4
gplus_username:  Cyrus5
disqus_username: Cyrus6

# Build settings
markdown: kramdown
highlighter: rouge
permalink: /:title/


# html minify
compress_html:
  clippings: all
  comments: all
  endings: []
  profile: false

# Links to include in menu navigation
# For external links add external: true
links:
  - title: Home
    url: /
  - title: Series
    url: /series
  - title: Tags
    url: /tags
  - title: About Me
    url: /about

# exclude my node related stuff
exclude: ['package.json', 'src', 'node_modules']
